#include <chrono>
#include <cmath>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <random>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#ifdef _WIN32
#define NOMINMAX
#include <winsock2.h>
#include <ws2tcpip.h>
using socket_t = SOCKET;
#else
#include <arpa/inet.h>
#include <netdb.h>
#include <sys/socket.h>
#include <unistd.h>
using socket_t = int;
#endif

namespace {

struct SocketRuntime {
    SocketRuntime() {
#ifdef _WIN32
        WSADATA data{};
        WSAStartup(MAKEWORD(2, 2), &data);
#endif
    }

    ~SocketRuntime() {
#ifdef _WIN32
        WSACleanup();
#endif
    }
};

void closeSocket(socket_t sock) {
#ifdef _WIN32
    closesocket(sock);
#else
    close(sock);
#endif
}

std::vector<double> randVector(int n, std::mt19937_64& rng) {
    std::normal_distribution<double> normal(0.0, 1.0);
    std::vector<double> values(n);
    for (double& value : values) {
        value = normal(rng);
    }
    return values;
}

std::vector<std::vector<double>> randMatrixSquare(int n, std::mt19937_64& rng) {
    std::normal_distribution<double> normal(0.0, 1.0);
    std::vector<std::vector<double>> matrix(n, std::vector<double>(n));
    for (auto& row : matrix) {
        for (double& value : row) {
            value = normal(rng);
        }
    }
    return matrix;
}

void applyGain(std::vector<double>& g) {
    for (std::size_t l = 0; l < g.size(); ++l) {
        const double ll = static_cast<double>(l + 1);
        const double gamma = 100.0 + (1.0 / 20.0) * ll * std::sqrt(ll);
        g[l] *= gamma;
    }
}

void appendNumber(std::ostringstream& out, double value) {
    out << std::setprecision(17) << value;
}

std::string buildPayloadJson(const std::vector<double>& g,
                             const std::vector<std::vector<double>>& h,
                             int imageSize,
                             std::int64_t seed) {
    std::ostringstream out;
    out << "{\"g\":[";
    for (std::size_t i = 0; i < g.size(); ++i) {
        if (i != 0) {
            out << ',';
        }
        appendNumber(out, g[i]);
    }

    out << "],\"H\":[";
    for (std::size_t i = 0; i < h.size(); ++i) {
        if (i != 0) {
            out << ',';
        }
        out << '[';
        for (std::size_t j = 0; j < h[i].size(); ++j) {
            if (j != 0) {
                out << ',';
            }
            appendNumber(out, h[i][j]);
        }
        out << ']';
    }

    out << "],\"params\":{\"max_iter\":10,\"tol\":0.0001},"
        << "\"image_size\":" << imageSize << ','
        << "\"seed\":" << seed << ','
        << "\"meta\":{\"note\":\"Payload generated by C++ client; same g is used by every implementation\"}}";
    return out.str();
}

bool sendAll(socket_t sock, const std::string& data) {
    std::size_t total = 0;
    while (total < data.size()) {
        const int sent = send(sock, data.data() + total, static_cast<int>(data.size() - total), 0);
        if (sent <= 0) {
            return false;
        }
        total += static_cast<std::size_t>(sent);
    }
    return true;
}

std::string postJson(const std::string& host, int port, const std::string& path, const std::string& body) {
    addrinfo hints{};
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;

    addrinfo* result = nullptr;
    const std::string portText = std::to_string(port);
    if (getaddrinfo(host.c_str(), portText.c_str(), &hints, &result) != 0) {
        throw std::runtime_error("nao foi possivel resolver o host");
    }

    socket_t sock = -1;
    for (addrinfo* ptr = result; ptr != nullptr; ptr = ptr->ai_next) {
        sock = socket(ptr->ai_family, ptr->ai_socktype, ptr->ai_protocol);
        if (sock == static_cast<socket_t>(-1)) {
            continue;
        }
        if (connect(sock, ptr->ai_addr, static_cast<int>(ptr->ai_addrlen)) == 0) {
            break;
        }
        closeSocket(sock);
        sock = -1;
    }
    freeaddrinfo(result);

    if (sock == static_cast<socket_t>(-1)) {
        throw std::runtime_error("nao foi possivel conectar ao servidor");
    }

    std::ostringstream request;
    request << "POST " << path << " HTTP/1.1\r\n"
            << "Host: " << host << ':' << port << "\r\n"
            << "Content-Type: application/json\r\n"
            << "Content-Length: " << body.size() << "\r\n"
            << "Connection: close\r\n\r\n"
            << body;

    if (!sendAll(sock, request.str())) {
        closeSocket(sock);
        throw std::runtime_error("erro ao enviar dados ao servidor");
    }

    std::string response;
    char buffer[8192];
    while (true) {
        const int received = recv(sock, buffer, sizeof(buffer), 0);
        if (received <= 0) {
            break;
        }
        response.append(buffer, buffer + received);
    }
    closeSocket(sock);

    const std::size_t headerEnd = response.find("\r\n\r\n");
    if (headerEnd == std::string::npos) {
        return response;
    }
    return response.substr(headerEnd + 4);
}

} // namespace

int main() {
    try {
        SocketRuntime sockets;

        const int m = 2048;
        const auto now = std::chrono::high_resolution_clock::now().time_since_epoch();
        const auto seed = std::chrono::duration_cast<std::chrono::nanoseconds>(now).count();
        std::mt19937_64 rng(static_cast<std::uint64_t>(seed));

        auto g = randVector(m, rng);
        applyGain(g);
        const auto h = randMatrixSquare(m, rng);

        const std::string payload = buildPayloadJson(g, h, m, seed);
        const std::string reply = postJson("localhost", 8080, "/reconstruct", payload);
        std::cout << "Server reply: " << reply << '\n';
    } catch (const std::exception& err) {
        std::cerr << "Erro ao enviar ao servidor: " << err.what() << '\n';
        return 1;
    }

    return 0;
}
